name: Metrics
on:
    watch:
        types: [started]
    push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: SYSU_Matrix License
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: SYSU_Matrix_2022_licenses.svg
          repo: SYSU_Matrix_2022
          template: repository
          base: ''
          plugin_licenses: yes
          plugin_licenses_ratio: yes
          plugin_licenses_legal: yes
      - name: My-Code-Footprint License
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: MFC_licenses.svg
          repo: My-Code-Footprint
          template: repository
          base: ''
          plugin_licenses: yes
          plugin_licenses_ratio: yes
          plugin_licenses_legal: yes
      - name: MATLAB-Learn License
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: ML_License.svg
          repo: MATLAB-Learn
          template: repository
          base: ''
          plugin_licenses: yes
          plugin_licenses_ratio: yes
          plugin_licenses_legal: yes
